# Generated by Django 5.2.1 on 2025-06-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_to_check', models.CharField(choices=[('product_name', 'Product Name'), ('category', 'Category'), ('merchant', 'Merchant')], max_length=32)),
                ('match_text', models.CharField(max_length=128)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('merchant', models.CharField(max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('eligible', models.BooleanField(default=False)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
